### ISSUE TITLE
Misleading Intro.

### ISSUE THREAD

**Issue by garyrussell** [spring-guides/gs-messaging-rabbitmq#6] opened 2015-05-13 20:04 UTC
>This guide walks you through the process of setting up a RabbitMQ AMQP server that publishes and subscribes to messages.

http://stackoverflow.com/questions/30223203/spring-rabbitmq-tutorial-results-in-connection-refused-error

**Comment by thirty3** [comment] 2015-05-13 20:11
I use Spring a lot, but have never contributed and this seems like low hanging fruit. I would love to update that guide for you. I will add having RabbitMQ instance under the what you'll need section with a link through to https://www.rabbitmq.com/download.html

**Comment by gregturn** [comment] 2015-05-13 20:14
The problem is the steps to set up rabbit are hidden inside the STS step. Adding a section header should patch the issue.

**Comment by gregturn** [comment] 2015-05-13 20:16
Fixed by https://github.com/spring-guides/gs-messaging-rabbitmq/commit/ad1fcf37ea41c21253336f073a73cb58004c79d3

**Closed by gregturn** 2015-05-13 20:16 UTC

**Comment by gregturn** [comment] 2015-05-13 20:19
@thirty3 this one took little effort. But feel free to checkout outstanding issues at http://issue-aggregator.guides.spring.io

**Comment by thirty3** [comment] 2015-05-13 20:22
@gregturn Cool, thanks :smile_cat:

**Comment by garyrussell** [comment] 2015-05-14 13:46
Thanks; sounds good.

Please be sure to "sign" the CLA before issuing a PR.

https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement

**Comment by garyrussell** [comment] 2015-05-14 13:47
Sorry for the noise, guys; I had an old page in my browser.
